import { beforeAll, describe, expect, it } from "vitest";
import {
	generateCSSVariables,
	generateTailwindPreset,
	generateNativeTokens,
} from "./generate.js";

describe("generateCSSVariables", () => {
	const output = generateCSSVariables();

	it("wraps in :root selector", () => {
		expect(output.startsWith(":root {")).toBe(true);
		expect(output.endsWith("}\n")).toBe(true);
	});

	it("includes color variables for all five families", () => {
		expect(output).toContain("--color-gray-500");
		expect(output).toContain("--color-primary-500");
		expect(output).toContain("--color-danger-500");
		expect(output).toContain("--color-success-500");
		expect(output).toContain("--color-warning-500");
	});

	it("includes spacing tokens", () => {
		expect(output).toContain("--spacing-4: 1rem");
		expect(output).toContain("--spacing-16: 4rem");
	});

	it("includes radius tokens", () => {
		expect(output).toContain("--radius-md: 0.375rem");
		expect(output).toContain("--radius-full: 9999px");
	});

	it("includes shadow tokens", () => {
		expect(output).toContain("--shadow-md");
		expect(output).toContain("--shadow-lg");
	});

	it("includes z-index tokens", () => {
		expect(output).toContain("--z-modal: 1040");
		expect(output).toContain("--z-tooltip: 1060");
	});

	it("includes font family tokens", () => {
		expect(output).toContain("--font-sans:");
		expect(output).toContain("--font-mono:");
	});
});

describe("generateTailwindPreset", () => {
	const code = generateTailwindPreset();
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	let preset: any;

	beforeAll(() => {
		// eval is safe here — this is generated, trusted code
		const mod = { exports: {} };
		const fn = new Function(
			"module",
			"exports",
			code.replace("export default ", "module.exports = "),
		);
		fn(mod, mod.exports);
		preset = mod.exports;
	});

	it("produces valid ESM with export default", () => {
		expect(code.startsWith("// Generated by @chariot/depot-tokens")).toBe(true);
		expect(code).toContain("export default");
	});

	it("has theme.extend with all 9 keys", () => {
		const keys = Object.keys(preset.theme.extend);
		expect(keys.sort()).toEqual([
			"borderRadius",
			"boxShadow",
			"colors",
			"fontFamily",
			"screens",
			"spacing",
			"transitionDuration",
			"transitionTimingFunction",
			"zIndex",
		]);
	});

	it("has all five color families", () => {
		expect(Object.keys(preset.theme.extend.colors).sort()).toEqual([
			"danger",
			"gray",
			"primary",
			"success",
			"warning",
		]);
	});

	it("uses CSS variable references with fallback", () => {
		expect(preset.theme.extend.colors.primary["500"]).toBe(
			"var(--color-primary-500, #3b82f6)",
		);
		expect(preset.theme.extend.colors.gray["50"]).toBe(
			"var(--color-gray-50, #f9fafb)",
		);
	});

	it("maps spacing to var() with rem fallback", () => {
		expect(preset.theme.extend.spacing["4"]).toBe("var(--spacing-4, 1rem)");
		expect(preset.theme.extend.spacing["16"]).toBe("var(--spacing-16, 4rem)");
	});

	it("maps borderRadius correctly", () => {
		expect(preset.theme.extend.borderRadius.md).toBe(
			"var(--radius-md, 0.375rem)",
		);
		expect(preset.theme.extend.borderRadius.full).toBe(
			"var(--radius-full, 9999px)",
		);
	});

	it("maps boxShadow correctly", () => {
		expect(preset.theme.extend.boxShadow.md).toBe(
			"var(--shadow-md, 0 4px 6px -1px rgb(0 0 0 / 0.1))",
		);
	});

	it("maps fontFamily as arrays with var()", () => {
		expect(Array.isArray(preset.theme.extend.fontFamily.sans)).toBe(true);
		expect(preset.theme.extend.fontFamily.sans[0]).toMatch(/^var\(--font-sans/);
		expect(Array.isArray(preset.theme.extend.fontFamily.mono)).toBe(true);
		expect(preset.theme.extend.fontFamily.mono[0]).toMatch(/^var\(--font-mono/);
	});

	it("maps zIndex to var() with numeric fallback", () => {
		expect(preset.theme.extend.zIndex.modal).toBe("var(--z-modal, 1040)");
		expect(preset.theme.extend.zIndex.tooltip).toBe("var(--z-tooltip, 1060)");
	});

	it("maps transitionDuration from motion tokens", () => {
		expect(preset.theme.extend.transitionDuration.fast).toBe("150ms");
		expect(preset.theme.extend.transitionDuration.slow).toBe("300ms");
	});

	it("maps transitionTimingFunction from motion easing", () => {
		expect(preset.theme.extend.transitionTimingFunction.ease).toBe(
			"cubic-bezier(0.4, 0, 0.2, 1)",
		);
	});

	it("maps screens from breakpoint tokens", () => {
		expect(preset.theme.extend.screens.md).toBe("768px");
		expect(preset.theme.extend.screens.lg).toBe("1024px");
	});
});

describe("generateNativeTokens", () => {
	const code = generateNativeTokens();
	// eslint-disable-next-line @typescript-eslint/no-explicit-any
	let mod: any;

	beforeAll(() => {
		const fn = new Function(
			"exports",
			code.replace("export const nativeTokens = ", "exports.nativeTokens = "),
		);
		const exports = {};
		fn(exports);
		mod = exports;
	});

	it("produces valid ESM with named export", () => {
		expect(code).toContain("export const nativeTokens");
	});

	it("has all 8 top-level token categories", () => {
		const keys = Object.keys(mod.nativeTokens).sort();
		expect(keys).toEqual([
			"breakpoint",
			"colors",
			"motion",
			"radius",
			"shadow",
			"spacing",
			"typography",
			"zIndex",
		]);
	});

	it("contains raw hex color values (not var() references)", () => {
		expect(mod.nativeTokens.colors.primary[500]).toBe("#3b82f6");
		expect(mod.nativeTokens.colors.gray[50]).toBe("#f9fafb");
	});

	it("contains raw spacing values", () => {
		expect(mod.nativeTokens.spacing[4]).toBe("1rem");
	});

	it("contains typography details", () => {
		expect(mod.nativeTokens.typography.fontFamily.sans).toContain("system-ui");
		expect(Array.isArray(mod.nativeTokens.typography.fontSize.base)).toBe(true);
	});

	it("contains breakpoint values", () => {
		expect(mod.nativeTokens.breakpoint.sm).toBe("640px");
		expect(mod.nativeTokens.breakpoint["2xl"]).toBe("1536px");
	});

	it("has motion easing values", () => {
		expect(mod.nativeTokens.motion.easing.easeIn).toBe(
			"cubic-bezier(0.4, 0, 1, 1)",
		);
	});
});
